apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
      app: dex
  name: dex
spec:
  template:
    metadata:
      labels:
        app: dex
      name: dex
    spec:
      containers:
        - name: dex
          image: norsknettarkiv/dex
          command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]

          ports:
          - name: http
            containerPort: 5556

          volumeMounts:
          - name: config
            mountPath: /etc/dex/cfg

      volumes:
      - name: config
        configMap:
          name: dex-config
          items:
          - key: config.yaml
            path: config.yaml

---
kind: Service
apiVersion: v1
metadata:
  name: dex
spec:
  type: ClusterIP
  ports:
    - name: dex
      port: 5556
      protocol: TCP
      targetPort: http
  selector:
    app: dex

