#Logging - Elasticsearch, fluentd and Kibana
---
apiVersion: v1
kind: Namespace
metadata:
  name: auau
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: auau
  labels:
      app: dex
  name: dex
spec:
  template:
    metadata:
      labels:
        app: dex
      name: dex
    spec:
      containers:
        - name: dex
          image: norsknettarkiv/dex
          command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]

          ports:
          - name: https
            containerPort: 5556

          volumeMounts:
          - name: config
            mountPath: /etc/dex/cfg
          #- name: tls
          #  mountPath: /etc/dex/tls

      volumes:
      - name: config
        configMap:
          name: dex-config
          items:
          - key: config.yaml
            path: config.yaml
      #- name: tls
      #  secret:
      #    secretName: dex.example.com.tls

---
kind: Service
apiVersion: v1
metadata:
  name: dex
  namespace: auau
spec:
  type: NodePort
  ports:
    - name: dex
      port: 5556
      protocol: TCP
      targetPort: 5556
      nodePort: 32000
  selector:
    app: dex

