---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: dtabs.l5d.io
spec:
  scope: Namespaced
  group: l5d.io
  version: v1alpha1
  names:
    kind: DTab
    plural: dtabs
    singular: dtab
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: namerd-config
data:
  config.yml: |-
    admin:
      ip: 0.0.0.0
      port: 9991

    namers:
    - kind: io.l5d.k8s
      host: localhost
      port: 8001

    storage:
      kind: io.l5d.k8s
      host: localhost
      port: 8001
      namespace: default

    interfaces:
    - kind: io.l5d.thriftNameInterpreter
      ip: 0.0.0.0
      port: 4100
    - kind: io.l5d.thriftNameInterpreter
      ip: 0.0.0.0
      port: 4101
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: 4180
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: 4181
    - kind: io.l5d.mesh
      ip: 0.0.0.0
      port: 4321
    - kind: io.l5d.mesh
      ip: 0.0.0.0
      port: 4322
    

---
kind: ReplicationController
apiVersion: v1
metadata:
  name: namerd
spec:
  replicas: 1
  selector:
    app: namerd
  template:
    metadata:
      labels:
        app: namerd
    spec:
      dnsPolicy: ClusterFirst
      volumes:
      - name: namerd-config
        configMap:
          name: namerd-config
      containers:
      - name: namerd
        image: buoyantio/namerd:1.3.5
        args:
        - /io.buoyant/namerd/config/config.yml
        resources:
          limits:
            memory: 2048Mi
          requests:
            cpu: 250m
            memory: 1024Mi
        ports:
        - name: thrift
          containerPort: 4100
        - name: http
          containerPort: 4180
        - name: mesh
          containerPort: 4321
        - name: admin
          containerPort: 9991
        volumeMounts:
        - name: "namerd-config"
          mountPath: "/io.buoyant/namerd/config"
          readOnly: true
      - name: kubectl
        image: buoyantio/kubectl:v1.8.5
        args:
        - "proxy"
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: namerd
spec:
  selector:
    app: namerd
  type: NodePort
  ports:
  - name: thrift
    port: 4100
  - name: http
    port: 4180
  - name: mesh
    port: 4321
  - name: admin
    port: 9991
    nodePort: 30989
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: namerctl-script
data:
  createNs.sh: |-
    #!/bin/sh

    set -e
    if namerctl dtab get grpc > /dev/null 2>&1; then
      echo "grpc namespace already exists"
    else
      echo "
        /srv                                => /#/io.l5d.k8s/default/grpc ;
        /grpc                               => /srv ;
        /svc/veidemann.api.Frontier         => /srv/veidemann-frontier ;
        /svc/veidemann.api.ContentWriter    => /srv/veidemann-contentwriter ;
        /svc/veidemann.api.Controller       => /srv/veidemann-controller ;
        /svc/veidemann.api.DnsResolver      => /srv/veidemann-dnsresolver ;
        /svc/veidemann.api.Harvester        => /srv/veidemann-harvester ;
        /svc/veidemann.api.RobotsEvaluator  => /srv/veidemann-robots ;
        /svc/veidemann.api.Status           => /srv/veidemann-controller ;
        /svc/veidemann.api.Report           => /srv/veidemann-controller ;
      " | namerctl dtab create grpc -
    fi
---
kind: Job
apiVersion: batch/v1
metadata:
  name: namerctl
spec:
  template:
    metadata:
      name: namerctl
    spec:
      volumes:
      - name: namerctl-script
        configMap:
          name: namerctl-script
          defaultMode: 0755
      containers:
      - name: namerctl
        image: linkerd/namerctl:0.8.6
        env:
        - name: NAMERCTL_BASE_URL
          value: http://namerd.default.svc.cluster.local:4180
        command:
        - "/namerctl/createNs.sh"
        volumeMounts:
        - name: "namerctl-script"
          mountPath: "/namerctl"
          readOnly: true
      restartPolicy: OnFailure
