apiVersion: batch/v1
kind: Job
metadata:
  name: initdb
spec:
  template:
    metadata:
      name: initdb
    spec:
      containers:
      - name: initdb
        image: norsknettarkiv/veidemann-db-initializer:1.0.0-SNAPSHOT
        env:
        - name: DB_HOST
          value: "rethink"
        - name: DB_PORT
          value: "28015"
      restartPolicy: Never
