kind: Template
apiVersion: v1
metadata:
  name: broprox
  annotations:
    description: A proxy based crawler
    tags: instant-app
labels:
  template: broprox

## PARAMETERS ##
parameters:
- name: BROPROX_HARVESTER_API_ROUTE
  displayName: Host name for broprox harvester api
  required: true

objects:
########################
## Broprox harvester  ##
########################
- kind: Route
  apiVersion: v1
  metadata:
    name: broprox-harvester
  spec:
    host: ${BROPROX_HARVESTER_API_ROUTE}
    port:
      targetPort: broprox-harvester-api
    tls:
      termination: edge
    to:
      kind: Service
      name: broprox-harvester
      weight: 100

- kind: Service
  apiVersion: v1
  metadata:
    name: broprox-harvester
  spec:
    ports:
    - name: broprox-harvester-api
      port: 9090
      targetPort: 9090
    - name: broprox-harvester-proxy
      port: 8080
      targetPort: 8080
    - name: broprox-browser-api
      port: 9222
      targetPort: 9222
    selector:
      deploymentconfig: broprox-harvester
    type: ClusterIP
    sessionAffinity: None

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: broprox-harvester
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 180
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      deploymentconfig: broprox-harvester
    template:
      metadata:
        labels:
          deploymentconfig: broprox-harvester
      spec:
        containers:
        - name: broprox-browser
          image: norsknettarkiv/chrome-headless
          ports:
          - containerPort: 9222
          env:
          - name: CHROME_OPTS
            value: "--proxy-server=localhost:8080 --ignore-certificate-errors --disable-web-security --allow-running-insecure-content"
          volumeMounts:
          - mountPath: /data
            name: workdir
        - name: broprox-harvester
          image: norsknettarkiv/broprox-harvester
          ports:
          - containerPort: 8080
          - containerPort: 9090
          env:
          - name: BROWSER_HOST
            value: "localhost"
          volumeMounts:
          - mountPath: /workdir
            name: workdir
        restartPolicy: Always
        dnsPolicy: ClusterFirst
        volumes:
        - emptyDir: {}
          name: workdir
