# Requires Docker Compose 1.6.0+ and Docker Engine 1.10.0+
version: '2.1'

volumes:
    harvester-workdir:
    rethink-data:

services:
    # RethinkDB
    db:
        image: rethinkdb:2.3
        ports:
            - "28015:28015"
            - "29015:29015"
            - "8888:8080"
        volumes:
            - rethink-data:/data

    db_initializer:
        image: norsknettarkiv/broprox-db-initializer
        depends_on:
            - db
        environment:
            - "DB_HOST=db"

    # Chrome headless
    browser:
        image: norsknettarkiv/chrome-headless
        ports:
            - "9222:9222"
        volumes:
            - harvester-workdir:/data
        environment:
            - "CHROME_OPTS=--ignore-certificate-errors --disable-web-security --allow-running-insecure-content --proxy-server=harvester:8080"

    # Broprox harvester
    harvester:
        image: norsknettarkiv/broprox-harvester
        ports:
            - "9191:8080"
            - "9090:9090"
        volumes:
             - harvester-workdir:/workdir
        depends_on:
            - db_initializer
            - browser
            - content-writer
            - testsites
            - tracer
        environment:
            - "BROWSER_HOST=browser"
            - "DB_HOST=db"
            - "CONTENT_WRITER_HOST=content-writer"
            - "CONTENT_WRITER_PORT=8080"
            - "DNS_SERVER=testsites"
            - "TRACER_URI=http://tracer:9411/api/v1/spans"

    # Broprox content writer
    content-writer:
        image: norsknettarkiv/broprox-contentwriter-service
        ports:
            - "9292:8080"
        volumes:
            - ./work/warcs:/warcs
            - ./work/writer:/workdir
        depends_on:
            - db_initializer
            - tracer
        environment:
            - "DB_HOST=db"
            - "TRACER_URI=http://tracer:9411/api/v1/spans"

    # Broprox frontier
    frontier:
        image: norsknettarkiv/broprox-frontier
        ports:
            - "7700:7700"
        volumes:
            - ./work/frontier:/workdir
        depends_on:
            - db_initializer
            - harvester
            - tracer
        environment:
            - "DB_HOST=db"
            - "HARVESTER_HOST=harvester"
            - "TRACER_URI=http://tracer:9411/api/v1/spans"

    testsites:
        image: testsites
#        ports:
#            - "80:80"
#            - "53:53"

    # Broprox controller
    controller:
        image: norsknettarkiv/broprox-controller
        ports:
            - "50051:50051"
        depends_on:
            - db_initializer
            - tracer
        environment:
            - "DB_HOST=db"
            - "FRONTIER_HOST=frontier"
            - "TRACER_URI=http://tracer:9411/api/v1/spans"

    # Zipkin
    tracer:
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
