# Requires Docker Compose 1.6.0+ and Docker Engine 1.10.0+
version: '2'

volumes:
    harvester-workdir:
    rethink-data:

services:
    # RethinkDB
    db:
        image: rethinkdb:2.3
        ports:
            - "28015:28015"
            - "29015:29015"
            - "8888:8080"
        volumes:
            - rethink-data:/data

    # Chrome headless
    browser:
        image: norsknettarkiv/chrome-headless
        ports:
            - "9222:9222"
        volumes:
            - harvester-workdir:/data
        environment:
            - "CHROME_OPTS=--ignore-certificate-errors --disable-web-security --allow-running-insecure-content --proxy-server=harvester:8080"

    # Broprox harvester
    harvester:
        image: norsknettarkiv/broprox-harvester
        ports:
            - "9191:8080"
            - "9090:9090"
        volumes:
             - harvester-workdir:/workdir
        links:
            - "db"
            - "browser"
            - "content-writer"
        environment:
            - "BROWSER_HOST=browser"
            - "DB_HOST=db"
            - "CONTENT_WRITER_HOST=content-writer"
            - "CONTENT_WRITER_PORT=8080"

    # Broprox content writer
    content-writer:
        image: norsknettarkiv/broprox-contentwriter-service
        ports:
            - "9292:8080"
        volumes:
            - ./work/warcs:/warcs
            - ./work/writer:/workdir
        links:
            - "db"
        environment:
            - "DB_HOST=db"

    # Broprox content writer
    frontier:
        image: norsknettarkiv/broprox-frontier
        ports:
            - "7700:7700"
        volumes:
            - ./work/frontier:/workdir
        links:
            - "db"
            - "harvester"
        environment:
            - "DB_HOST=db"
            - "HARVESTER_HOST=harvester"
