# Requires Docker Compose 1.6.0+ and Docker Engine 1.10.0+
version: '2'

volumes:
    harvester-workdir:
    rethink-data:

services:
    # RethinkDB
    db:
        image: rethinkdb:2.3
        ports:
            - "28015:28015"
            - "29015:29015"
            - "8888:8080"
        volumes:
            - rethink-data:/data

    # Chrome headless
    browser:
        image: norsknettarkiv/chrome-headless
        ports:
            - "9222:9222"
        volumes:
            - harvester-workdir:/data
        environment:
            - "CHROME_OPTS=--ignore-certificate-errors --disable-web-security --allow-running-insecure-content --proxy-server=harvester:8080"

    # Veidemann harvester
    harvester:
        image: norsknettarkiv/veidemann-harvester
        ports:
            - "9191:8080"
            - "9090:9090"
        volumes:
             - harvester-workdir:/workdir
        links:
            - "db"
            - "browser"
            - "content-writer"
            - "tracer"
        environment:
            - "BROWSER_HOST=browser"
            - "DB_HOST=db"
            - "CONTENT_WRITER_HOST=content-writer"
            - "CONTENT_WRITER_PORT=8080"
            - "TRACER_URI=http://tracer:9411/api/v1/spans"

    # Veidemann content writer
    content-writer:
        image: norsknettarkiv/veidemann-contentwriter-service
        ports:
            - "9292:8080"
        volumes:
            - ./work/warcs:/warcs
            - ./work/writer:/workdir
        links:
            - "db"
            - "tracer"
        environment:
            - "DB_HOST=db"
            - "TRACER_URI=http://tracer:9411/api/v1/spans"

    # Veidemann frontier
    frontier:
        image: norsknettarkiv/veidemann-frontier
        ports:
            - "7700:7700"
        volumes:
            - ./work/frontier:/workdir
        links:
            - "db"
            - "harvester"
            - "tracer"
        environment:
            - "DB_HOST=db"
            - "HARVESTER_HOST=harvester"
            - "TRACER_URI=http://tracer:9411/api/v1/spans"

    # Veidemann controller
    controller:
        image: norsknettarkiv/veidemann-controller
        ports:
            - "50051:50051"
        links:
            - "db"
            - "tracer"
        environment:
            - "DB_HOST=db"
            - "TRACER_URI=http://tracer:9411/api/v1/spans"

    # Zipkin
    tracer:
        image: openzipkin/zipkin
        ports:
            - "9411:9411"
